server:
  port: 38092

spring:
  application:
    name: tcl-server
  mvc:
    converters:
      preferred-json-mapper: jackson
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: now()
      logic-not-delete-value: 'NULL'

#swagger:
#  enable: true
#  application-name: ${spring.application.name}
#  application-version: 1.0
#  application-description: springfox swagger3
#  try-host: http://localhost:${server.port}

logging:
  level:
    com.sipc.topicserver.mapper: debug